"""changes in task date

Revision ID: f2f3313ee067
Revises: 3c10c18d081b
Create Date: 2025-04-12 17:29:05.215838

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f3313ee067'
down_revision: Union[str, None] = '3c10c18d081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'deadline',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               nullable=False,
               postgresql_using='deadline::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'deadline',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='deadline::text')
    # ### end Alembic commands ###
