services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6543:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  lab_1:
    build:
      context: ../lab_1
      dockerfile: Dockerfile
    restart: always
    container_name: lab_1
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  parser_worker:
    build:
      context: ./lab_3
      dockerfile: Dockerfile
    container_name: parser_worker
    env_file: .env
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - postgres
      - redis

  parser_api:
    build:
      context: ./lab_3
      dockerfile: Dockerfile
    container_name: parser_api
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis