site_name: 'Отчеты к лабораторным работам по веб-программированию'
nav:
  - Главная страница: index.md
  - Лабораторная работа 1: Lr1/task.md
  - Лабораторная работа 2:
      - Задача 1. Различия между threading, multiprocessing и async в Python: Lr2/sum.md
      - Задача 2. Параллельный парсинг веб-страниц с сохранением в базу данных: Lr2/parsing.md
  - Лабораторная работа 3:
      - Подзадача 1. Упаковка FastAPI приложения, базы данных и парсера данных в Docker: Lr3/task1.md
      - Подзадача 2. Вызов парсера из FastAPI: Lr3/task2.md
      - Подзадача 3. Вызов парсера из FastAPI: Lr3/task3.md



theme:
  name: material
