"""missed boolean added

Revision ID: 5d43e6acde97
Revises: 
Create Date: 2025-05-08 22:32:55.478961
	
"""
from typing import Sequence, Union

from alembic import op
import sqlmodel

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d43e6acde97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('missed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'missed')
    # ### end Alembic commands ###
