"""Remove content field from Message

Revision ID: 3cabda4fa3e7
Revises: ae7ecd9c6687
Create Date: 2025-05-25 13:55:01.594538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cabda4fa3e7'
down_revision: Union[str, None] = 'ae7ecd9c6687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
