FROM python:3.10-slim

WORKDIR /app

# Скопировать и установить зависимости
COPY parser/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код
COPY parser/ ./

# Экспонируем порт
EXPOSE 8001

# Запускаем FastAPI-приложение
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]
