# Dockerfile.api
FROM python:3.10-slim

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем список зависимостей и устанавливаем их
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всё содержимое папки api в контейнер
COPY api/ ./

# Пробрасываем порт
EXPOSE 8000

# Команда запуска
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
