"""Add GoalUserLink table

Revision ID: 2713b8185ab3
Revises: 71e6c06efb73
Create Date: 2025-04-22 10:55:01.443813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2713b8185ab3'
down_revision: Union[str, None] = '71e6c06efb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goalnotificationlink')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalnotificationlink',
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], name='goalnotificationlink_goal_id_fkey'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='goalnotificationlink_notification_id_fkey'),
    sa.PrimaryKeyConstraint('goal_id', 'notification_id', name='goalnotificationlink_pkey')
    )
    # ### end Alembic commands ###
