site_name: "Documentation"
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

nav:
  - Home: index.md
  - Lab1:
    - Lab 1: lab1/lab1.md
    - endpoints: lab1/endpoints.md
  - Lab2:
    - task1: lab2/task1.md
    - task2: lab2/task2.md
  - Lab3:
    - Lab 3: lab3/lab3.md
  - Leetcodes:
    - Leetcodes: leetcodes/leetcodes.md
