"""new_id_field

Revision ID: 8826d60e9089
Revises: b29597323835
Create Date: 2025-04-08 00:33:40.909359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8826d60e9089'
down_revision: Union[str, None] = 'b29597323835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    # 1. Создание ENUM типа в PostgreSQL
    status_enum = postgresql.ENUM('available', 'exchanged', name='status')
    status_enum.create(op.get_bind())

    # 2. Преобразование типа колонки через USING
    op.execute("ALTER TABLE book ALTER COLUMN status TYPE status USING status::status")

    op.add_column('exchangerequest', sa.Column('requested_book_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exchangerequest', 'book', ['requested_book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchangerequest', type_='foreignkey')
    op.drop_column('exchangerequest', 'requested_book_id')
    op.alter_column('book', 'status',
               existing_type=sa.Enum('available', 'exchanged', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('exchange',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='exchange_book_id_fkey'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='exchange_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='exchange_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exchange_pkey')
    )
    # ### end Alembic commands ###
