"""update

Revision ID: b29597323835
Revises: af0cdedce352
Create Date: 2025-03-23 18:12:06.927785

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b29597323835'
down_revision: Union[str, None] = 'af0cdedce352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'status',
               existing_type=postgresql.ENUM('available', 'exchanged', name='status'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index('ix_genre_name', table_name='genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_genre_name', 'genre', ['name'], unique=False)
    op.alter_column('book', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('available', 'exchanged', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###
