"""init migration

Revision ID: d31817a5a4eb
Revises: 
Create Date: 2025-03-22 20:24:51.907011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31817a5a4eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizer')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('participant')
    op.drop_table('hackathon')
    op.drop_table('team')
    op.drop_table('uploadedtask')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadedtask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name='uploadedtask_participant_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='uploadedtask_task_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='uploadedtask_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='uploadedtask_pkey')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('team_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='team_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('hackathon',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hackathon_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hackathon_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hackathon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], name='participant_hackathon_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='participant_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participant_pkey')
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('evaluation_criteria', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hackathon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], name='task_hackathon_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'admin', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('organizer',
    sa.Column('hackathon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], name='organizer_hackathon_id_fkey'),
    sa.PrimaryKeyConstraint('hackathon_id', 'user_id', name='organizer_pkey')
    )
    # ### end Alembic commands ###
