"""working fine

Revision ID: b5bdfef7652c
Revises: 743a4dc5bf13
Create Date: 2025-05-07 13:10:22.055046

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bdfef7652c'
down_revision: Union[str, None] = '743a4dc5bf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
