"""add note field to TransactionTagLink

Revision ID: d153390e44c0
Revises: 3774d9d4cc9d
Create Date: 2025-05-12 14:01:34.076467

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd153390e44c0'
down_revision: Union[str, None] = '3774d9d4cc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactiontaglink', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactiontaglink', 'note')
    # ### end Alembic commands ###
