"""Initial migration

Revision ID: 6269ee0ad2da
Revises: b5f71bde4722
Create Date: 2025-04-24 12:12:55.963512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6269ee0ad2da'
down_revision: Union[str, None] = 'b5f71bde4722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Create a default project for existing sprints
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO project (name, description)
        VALUES ('Default Project', 'Default project for existing sprints')
        RETURNING id
    """))
    result = connection.execute(sa.text("SELECT id FROM project ORDER BY id DESC LIMIT 1"))
    default_project_id = result.scalar()

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'developer', 'manager', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add project_id column as nullable first
    op.add_column('sprint', sa.Column('project_id', sa.Integer(), nullable=True))
    
    # Update existing sprints to use the default project
    op.execute(f'UPDATE sprint SET project_id = {default_project_id}')
    
    # Now make the column not nullable
    op.alter_column('sprint', 'project_id', nullable=False)
    
    op.create_foreign_key(None, 'sprint', 'project', ['project_id'], ['id'])
    op.add_column('task', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'assignee_id')
    op.drop_constraint(None, 'sprint', type_='foreignkey')
    op.drop_column('sprint', 'project_id')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ### 