DEFAULT_GENRES = [
    "Science Fiction",
    "Mystery",
    "Fantasy",
    "Romance",
    "Historical Fiction",
    "Biography",
    "Horror",
    "Comedy",
    "Drama",
    "Thriller",
    "Adventure",
    "Dystopian",
    "Self-Help",
    "Poetry",
    "Crime",
    "Psychological Fiction",
    "Philosophy",
    "Children’s Literature",
    "Young Adult",
    "Graphic Novel",
    "Literary Fiction",
    "Action",
    "Cyberpunk",
    "Steampunk",
    "Gothic Fiction",
    "Political Fiction",
    "Mythology",
    "Spirituality",
    "Travel",
    "Business",
    "Education",
    "Science",
    "Technology",
    "Medical Fiction",
    "War Fiction",
    "Western",
    "Sports",
    "Paranormal",
    "Folklore",
    "Epic",
    "Satire",
    "Classic Literature",
]