FROM python:3.10-slim

WORKDIR /usr/src/parser

COPY parser_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY parser_service/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]