"""Updated models

Revision ID: 864e05f1c7ce
Revises: eca477bda10f
Create Date: 2025-03-29 23:20:36.369096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel, Field


# revision identifiers, used by Alembic.
revision: str = '864e05f1c7ce'
down_revision: Union[str, None] = 'eca477bda10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_reviewed_user_id', table_name='review')
    op.drop_index('ix_review_reviewer_id', table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewed_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['user.id'], name='review_reviewed_user_id_fkey'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name='review_reviewer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_pkey')
    )
    op.create_index('ix_review_reviewer_id', 'review', ['reviewer_id'], unique=False)
    op.create_index('ix_review_reviewed_user_id', 'review', ['reviewed_user_id'], unique=False)
    # ### end Alembic commands ###
