"""Remove unique constraint from Preference.name

Revision ID: 9269c9639c64
Revises: 864e05f1c7ce
Create Date: 2025-04-06 17:54:21.180121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel, Field


# revision identifiers, used by Alembic.
revision: str = '9269c9639c64'
down_revision: Union[str, None] = '864e05f1c7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preference_name', table_name='preference')
    op.create_index(op.f('ix_preference_name'), 'preference', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_name'), table_name='preference')
    op.create_index('ix_preference_name', 'preference', ['name'], unique=True)
    # ### end Alembic commands ###
