"""Updated models

Revision ID: eca477bda10f
Revises: 72d946bfe7bf
Create Date: 2025-03-29 23:14:41.272055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel, Field


# revision identifiers, used by Alembic.
revision: str = 'eca477bda10f'
down_revision: Union[str, None] = '72d946bfe7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
