version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: timemanager_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d timemanager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  parser:
    build:
      context: ./parser_service_app
      dockerfile: Dockerfile
    volumes:
      - ./parser_service_app:/parser_service_app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:password123@db:5432/timemanager_db
      - DATABASE_URL_ASYNC=postgresql+asyncpg://admin:password123@db:5432/timemanager_db
    depends_on:
      db:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:password123@db:5432/timemanager_db
      - DATABASE_URL_ASYNC=postgresql+asyncpg://admin:password123@db:5432/timemanager_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:password123@db:5432/timemanager_db
      - DATABASE_URL_ASYNC=postgresql+asyncpg://admin:password123@db:5432/timemanager_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
