"""add owner_id to book

Revision ID: 24ab099d5304
Revises: 6212198d7f80
Create Date: 2025-06-19 12:03:50.192468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ab099d5304'
down_revision: Union[str, Sequence[str], None] = '6212198d7f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    op.alter_column('exchange_requests', 'sender_book_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    op.alter_column('exchange_requests', 'sender_book_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###
