"""Make sender_book_id nullable in exchange_requests

Revision ID: 870a45b6aac0
Revises: 24ab099d5304
Create Date: 2025-06-19 13:19:04.832399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870a45b6aac0'
down_revision: Union[str, Sequence[str], None] = '24ab099d5304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_requests', 'sender_book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_requests', 'sender_book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
