"""Create all tables

Revision ID: 01cd4845fd8a
Revises: 
Create Date: 2025-05-19 00:27:18.752174

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01cd4845fd8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('parsed_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), nullable=False),
                    sa.Column('evaluation_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('team',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('userteam',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('leader', 'developer', 'designer', 'tester', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('work',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=True),
                    sa.Column('file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
                    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('evaluation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('work_id', sa.Integer(), nullable=True),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('work')
    op.drop_table('userteam')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('task')
    op.drop_table('page')
    # ### end Alembic commands ###
