"""transactions were changed

Revision ID: 19945fac3f6f
Revises: d567fe3b46e7
Create Date: 2025-04-10 23:41:50.925461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19945fac3f6f'
down_revision: Union[str, None] = 'd567fe3b46e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_user_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_category_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'category', ['category_id'], ['category_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_category_id_fkey', 'transaction', 'category', ['category_id'], ['category_id'])
    op.create_foreign_key('transaction_user_id_fkey', 'transaction', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
