"""add_password_field

Revision ID: 70cd16d25371
Revises: b376d04f13d3
Create Date: 2025-04-28 19:18:55.642859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Добавьте этот импорт
from sqlmodel import SQLModel  # Добавьте этот импорт
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '70cd16d25371'
down_revision: Union[str, None] = 'b376d04f13d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
