"""status number removed

Revision ID: 39d949609fe8
Revises: cac0e2ff569a
Create Date: 2025-04-09 23:26:03.549508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39d949609fe8'
down_revision: Union[str, None] = 'cac0e2ff569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchangestatus', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangestatus', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
