"""book in exchange changed to library

Revision ID: c48c4e278019
Revises: 54bb5ce13006
Create Date: 2025-04-15 23:21:06.159509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c48c4e278019'
down_revision: Union[str, None] = '54bb5ce13006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangerequest', sa.Column('library_id', sa.Integer(), nullable=False))
    op.drop_constraint('exchangerequest_book_id_fkey', 'exchangerequest', type_='foreignkey')
    op.create_foreign_key(None, 'exchangerequest', 'library', ['library_id'], ['id'])
    op.drop_column('exchangerequest', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangerequest', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exchangerequest', type_='foreignkey')
    op.create_foreign_key('exchangerequest_book_id_fkey', 'exchangerequest', 'book', ['book_id'], ['id'])
    op.drop_column('exchangerequest', 'library_id')
    # ### end Alembic commands ###
