site_name: My Docs
nav:
  - Home: index.md
  - Лабораторная 1:
      - Введение: Lr1/main.md
      - Модели: Lr1/models.md
      - Документация: Lr1/docs.md
  - Лабораторная 2:
      - Введение: Lr2/main.md
      - Выполнение: Lr2/making.md
  - Лабораторная 3:
      - Введение: Lr3/main.md
      - Выполнение: Lr3/making.md
  - Литкоды: leetcodes/main.md
theme:
  name: dracula
plugins:
  - render_swagger:
      allow_arbitrary_locations : true