import sqlmodel

"""Add email column to user table

Revision ID: f57de418561a
Revises: 52794e655198
Create Date: 2025-04-26 20:26:04.992594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f57de418561a'
down_revision: Union[str, None] = '52794e655198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    op.add_column('goal', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('goal', 'name')
    op.drop_column('goal', 'current_amount')

    # Изменение типа столбца 'date' в 'transaction' с VARCHAR на DateTime
    op.alter_column('transaction', 'date',
                    existing_type=sa.VARCHAR(),
                    type_=sa.DateTime(),
                    existing_nullable=False,
                    postgresql_using='date::timestamp')

    op.drop_column('transaction', 'description')
    op.add_column('transactioncategory', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('transactioncategory', 'amount')
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'email')
    op.add_column('transactioncategory',
                  sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transactioncategory', 'note')
    op.add_column('transaction', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Откат изменения типа столбца 'date' с DateTime на VARCHAR
    op.alter_column('transaction', 'date',
                    existing_type=sa.DateTime(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False,
                    postgresql_using='date::date')

    op.add_column('goal',
                  sa.Column('current_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('goal', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'description')
    op.add_column('category', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
