"""user added

Revision ID: 670935005fb6
Revises: 
Create Date: 2025-04-02 14:42:59.925706

"""
from typing import Sequence, Union
from sqlmodel import SQLModel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670935005fb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('librarylink')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('librarylink',
    sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='librarylink_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='librarylink_user_id_fkey'),
    sa.PrimaryKeyConstraint('library_id', 'user_id', 'book_id', name='librarylink_pkey')
    )
    # ### end Alembic commands ###
