"""add cancelled to enum

Revision ID: 4b5fc5ca1ca1
Revises: 1174f325cec7
Create Date: 2025-05-03 17:28:40.970194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b5fc5ca1ca1'
down_revision: Union[str, None] = '1174f325cec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
