"""add cancelled to enum_2

Revision ID: 7b3f8ee24dab
Revises: 4b5fc5ca1ca1
Create Date: 2025-05-03 17:30:05.281359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b3f8ee24dab'
down_revision: Union[str, None] = '4b5fc5ca1ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE triprequeststatus ADD VALUE IF NOT EXISTS 'cancelled'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
