import sqlmodel
"""prefences added

Revision ID: 9484b82eab5c
Revises: 
Create Date: 2025-05-02 21:29:06.748831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9484b82eab5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizerprofile', 'phone_number')
    op.alter_column('trip', 'organizer_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'])
    op.drop_column('trip', 'departure_date')
    op.add_column('user', sa.Column('preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'preferences')
    op.add_column('trip', sa.Column('departure_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.alter_column('trip', 'organizer_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('organizerprofile', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
