"""add sender_book_id to ExchangeRequest

Revision ID: 0e9af6f9f37b
Revises: 8826d60e9089
Create Date: 2025-04-08 01:08:14.854105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9af6f9f37b'
down_revision: Union[str, None] = '8826d60e9089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangerequest', sa.Column('sender_book_id', sa.Integer(), nullable=False))
    op.drop_constraint('exchangerequest_book_id_fkey', 'exchangerequest', type_='foreignkey')
    op.create_foreign_key(None, 'exchangerequest', 'book', ['sender_book_id'], ['id'])
    op.drop_column('exchangerequest', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangerequest', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exchangerequest', type_='foreignkey')
    op.create_foreign_key('exchangerequest_book_id_fkey', 'exchangerequest', 'book', ['book_id'], ['id'])
    op.drop_column('exchangerequest', 'sender_book_id')
    # ### end Alembic commands ###
