"""Really making Outdated

Revision ID: 2a99ede994c1
Revises: 1353c5100d17
Create Date: 2025-03-18 21:52:12.531532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a99ede994c1'
down_revision: Union[str, None] = '1353c5100d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ENUM_NAME = "swapstatus"

NEW_STATUS = "OUTDATED"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE '{NEW_STATUS}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
