"""Remove rating, add publisher to Book

Revision ID: 330bb9470001
Revises: 0489cc4f27b8
Create Date: 2025-03-15 16:08:03.683756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '330bb9470001'
down_revision: Union[str, None] = '0489cc4f27b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('book', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('book', 'publisher')
    # ### end Alembic commands ###
