"""Update Genre: make name unique

Revision ID: 52eafc7b634f
Revises: 94589ce8a2f2
Create Date: 2025-03-16 14:08:57.885687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52eafc7b634f'
down_revision: Union[str, None] = '94589ce8a2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    # ### end Alembic commands ###
