"""Update User (add info) and Offer (add created_at)

Revision ID: 681e33a6cbb9
Revises: 2a99ede994c1
Create Date: 2025-03-21 00:50:40.136461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '681e33a6cbb9'
down_revision: Union[str, None] = '2a99ede994c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferences', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'info')
    op.drop_column('offer', 'created_at')
    # ### end Alembic commands ###
