"""Refactor ownership and offer

Revision ID: 94589ce8a2f2
Revises: 330bb9470001
Create Date: 2025-03-15 16:54:42.783194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94589ce8a2f2'
down_revision: Union[str, None] = '330bb9470001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_book_id'), 'ownership', ['book_id'], unique=False)
    op.create_index(op.f('ix_ownership_user_id'), 'ownership', ['user_id'], unique=False)
    op.add_column('offer', sa.Column('ownership_id', sa.Integer(), nullable=False))
    op.add_column('offer', sa.Column('is_open', sa.Boolean(), nullable=False))
    op.drop_index('ix_offer_book_id', table_name='offer')
    op.drop_index('ix_offer_user_id', table_name='offer')
    op.create_index(op.f('ix_offer_ownership_id'), 'offer', ['ownership_id'], unique=False)
    op.drop_constraint('offer_book_id_fkey', 'offer', type_='foreignkey')
    op.drop_constraint('offer_user_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'ownership', ['ownership_id'], ['id'])
    op.drop_column('offer', 'book_id')
    op.drop_column('offer', 'user_id')
    op.drop_column('offer', 'is_actual')
    op.add_column('swaprequest', sa.Column('get_offer_id', sa.Integer(), nullable=False))
    op.add_column('swaprequest', sa.Column('give_offer_id', sa.Integer(), nullable=False))
    op.drop_index('ix_swaprequest_offer_own_id', table_name='swaprequest')
    op.drop_index('ix_swaprequest_request_own_id', table_name='swaprequest')
    op.create_index(op.f('ix_swaprequest_get_offer_id'), 'swaprequest', ['get_offer_id'], unique=False)
    op.create_index(op.f('ix_swaprequest_give_offer_id'), 'swaprequest', ['give_offer_id'], unique=False)
    op.drop_constraint('swaprequest_request_own_id_fkey', 'swaprequest', type_='foreignkey')
    op.drop_constraint('swaprequest_offer_own_id_fkey', 'swaprequest', type_='foreignkey')
    op.create_foreign_key(None, 'swaprequest', 'offer', ['give_offer_id'], ['id'])
    op.create_foreign_key(None, 'swaprequest', 'offer', ['get_offer_id'], ['id'])
    op.drop_column('swaprequest', 'offer_own_id')
    op.drop_column('swaprequest', 'request_own_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaprequest', sa.Column('request_own_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('swaprequest', sa.Column('offer_own_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'swaprequest', type_='foreignkey')
    op.drop_constraint(None, 'swaprequest', type_='foreignkey')
    op.create_foreign_key('swaprequest_offer_own_id_fkey', 'swaprequest', 'offer', ['offer_own_id'], ['id'])
    op.create_foreign_key('swaprequest_request_own_id_fkey', 'swaprequest', 'offer', ['request_own_id'], ['id'])
    op.drop_index(op.f('ix_swaprequest_give_offer_id'), table_name='swaprequest')
    op.drop_index(op.f('ix_swaprequest_get_offer_id'), table_name='swaprequest')
    op.create_index('ix_swaprequest_request_own_id', 'swaprequest', ['request_own_id'], unique=False)
    op.create_index('ix_swaprequest_offer_own_id', 'swaprequest', ['offer_own_id'], unique=False)
    op.drop_column('swaprequest', 'give_offer_id')
    op.drop_column('swaprequest', 'get_offer_id')
    op.add_column('offer', sa.Column('is_actual', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('offer', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_user_id_fkey', 'offer', 'user', ['user_id'], ['id'])
    op.create_foreign_key('offer_book_id_fkey', 'offer', 'book', ['book_id'], ['id'])
    op.drop_index(op.f('ix_offer_ownership_id'), table_name='offer')
    op.create_index('ix_offer_user_id', 'offer', ['user_id'], unique=False)
    op.create_index('ix_offer_book_id', 'offer', ['book_id'], unique=False)
    op.drop_column('offer', 'is_open')
    op.drop_column('offer', 'ownership_id')
    op.drop_index(op.f('ix_ownership_user_id'), table_name='ownership')
    op.drop_index(op.f('ix_ownership_book_id'), table_name='ownership')
    op.drop_table('ownership')
    # ### end Alembic commands ###
