"""Remove Unique for ownership

Revision ID: b103aca7f2b3
Revises: d58ea03aaad4
Create Date: 2025-03-23 02:34:28.773503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b103aca7f2b3'
down_revision: Union[str, None] = 'd58ea03aaad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_current', 'ownership', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_book_current', 'ownership', ['book_id', 'is_current'])
    # ### end Alembic commands ###
