"""Update Offer: set ownership_id to delete cascade

Revision ID: d58ea03aaad4
Revises: 7886aad662af
Create Date: 2025-03-23 02:09:46.864310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd58ea03aaad4'
down_revision: Union[str, None] = '7886aad662af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'ownership_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('offer_ownership_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'ownership', ['ownership_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_ownership_id_fkey', 'offer', 'ownership', ['ownership_id'], ['id'])
    op.alter_column('offer', 'ownership_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
