"""Update ownership (add unique) and offer (set cascade delete from ownership)

Revision ID: eb578d89ca9f
Revises: 52eafc7b634f
Create Date: 2025-03-16 23:54:59.463730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb578d89ca9f'
down_revision: Union[str, None] = '52eafc7b634f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offer_ownership_id', table_name='offer')
    op.create_index(op.f('ix_offer_ownership_id'), 'offer', ['ownership_id'], unique=True)
    op.create_unique_constraint('uq_book_current', 'ownership', ['book_id', 'is_current'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_current', 'ownership', type_='unique')
    op.drop_index(op.f('ix_offer_ownership_id'), table_name='offer')
    op.create_index('ix_offer_ownership_id', 'offer', ['ownership_id'], unique=False)
    # ### end Alembic commands ###
