"""Update SwapRequest: add outdated status and trigger for offer change

Revision ID: fd5b99fb606a
Revises: dc7c3c7273a3
Create Date: 2025-03-18 16:54:12.704533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd5b99fb606a'
down_revision: Union[str, None] = 'dc7c3c7273a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swaprequest', 'get_offer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swaprequest', 'get_offer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
