"""fix budget schema

Revision ID: c0838ee54b7f
Revises: 38bd30f3ac2f
Create Date: 2025-04-13 00:01:02.870250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0838ee54b7f'
down_revision: Union[str, None] = '38bd30f3ac2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     'budget',
    #     sa.Column('month', sa.Integer(), nullable=False),
    #     sa.Column('year', sa.Integer(), nullable=False),
    #     sa.Column('limit', sa.Float(), nullable=False),
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('user_id', sa.Integer(), nullable=False),
    #     sa.Column(
    #         'category',
    #         sa.Enum(
    #             'food', 'transport', 'salary', 'entertainment', 'health', 'other',
    #             name='categorytype',
    #             create_type=False  # Не создавать ENUM повторно
    #         ),
    #         nullable=False
    #     ),
    #     sa.ForeignKeyConstraint(['user_id'], ['user.id']),
    #     sa.PrimaryKeyConstraint('id')
    # )
    op.drop_column('transaction', 'category_id')
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('budget')
    # ### end Alembic commands ###
