FROM python:3.13

ARG APP=app

WORKDIR /${APP}

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt


COPY src/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]