FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app

CMD ["uvicorn", "app.services.parser_service:app", "--host", "0.0.0.0", "--port", "8001", "--reload"] 